import { S3Client } from '@aws-sdk/client-s3';
import { createPresignedPost } from '@aws-sdk/s3-presigned-post';
import { randomUUID } from 'node:crypto';
// `env` is generated by Amplify once storage access is granted (see storage/resource.ts).
// It exposes the uploads bucket name in a type-safe way. Red squiggle before the
// first `ampx sandbox` run is expected — the file is generated at deploy time.
import { env } from '$amplify/env/get-upload-url';
import type { Schema } from '../../data/resource';
import { readSessionToken } from '../session-token';

// Only these image types are accepted for a menu upload.
const ALLOWED_CONTENT_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']);
// Only these extensions may appear in a key (derived from the content type above).
const EXTENSION: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
};
// How long the presigned POST policy is valid, in seconds.
const UPLOAD_URL_TTL_SECONDS = 300;
// S3-enforced size bounds for one page. The browser also checks 10 MB, but that is
// client-side courtesy only — this policy condition is the real cap: S3 itself rejects
// a body outside the range, so a scripted caller can't dump a multi-GB object on us.
const MIN_UPLOAD_BYTES = 1;
const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

const s3 = new S3Client();

export const handler: Schema['getUploadUrl']['functionHandler'] = async (event) => {
  const { contentType, sessionToken } = event.arguments;

  // Proof-of-humanness AND session identity in one step: the sessionId comes from the
  // SIGNED token, never from a client argument. This is what makes menu/<sessionId>/ a
  // real ownership boundary — a caller cannot choose someone else's prefix. No valid
  // token, no presigned URL. The exact message matters: the frontend detects it to
  // auto-renew and retry.
  const session = readSessionToken(sessionToken, env.SESSION_TOKEN_SECRET);
  if (!session) {
    throw new Error('Session expired — please try again.');
  }

  // Never trust the client: validate the declared MIME type before signing anything.
  if (!ALLOWED_CONTENT_TYPES.has(contentType)) {
    throw new Error(`Unsupported content type: ${contentType}`);
  }

  // Key is fully server-derived: signed sessionId + random object id + a fixed
  // extension from the (validated) content type. Nothing the client sent shapes the path.
  const s3Key = `menu/${session.sessionId}/${randomUUID()}.${EXTENSION[contentType]}`;

  // Presigned POST, not PUT: only a POST policy can carry `content-length-range`, which
  // S3 enforces server-side at upload time. Every entry in `Fields` also becomes an
  // exact-match policy condition, so the key and content type are pinned too — the
  // caller can upload exactly this object, at this type, within the size bounds, and
  // nothing else.
  const { url, fields } = await createPresignedPost(s3, {
    Bucket: env.SHISHA_MENU_UPLOADS_BUCKET_NAME,
    Key: s3Key,
    Conditions: [['content-length-range', MIN_UPLOAD_BYTES, MAX_UPLOAD_BYTES]],
    Fields: { 'Content-Type': contentType },
    Expires: UPLOAD_URL_TTL_SECONDS,
  });

  // The policy fields must be echoed back verbatim in the upload form (see the client's
  // uploadPage) — serialized as JSON because AppSync custom types can't carry a map.
  return { uploadUrl: url, formFields: JSON.stringify(fields), s3Key };
};
