import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { randomUUID } from 'node:crypto';
// `env` is generated by Amplify once storage access is granted (see storage/resource.ts).
// It exposes the uploads bucket name in a type-safe way. Red squiggle before the
// first `ampx sandbox` run is expected — the file is generated at deploy time.
import { env } from '$amplify/env/get-upload-url';
import type { Schema } from '../../data/resource';
import { readSessionToken } from '../session-token';

// Only these image types are accepted for a menu upload.
const ALLOWED_CONTENT_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']);
// Only these extensions may appear in a key (derived from the content type above).
const EXTENSION: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
};
// How long the presigned PUT URL is valid, in seconds.
const UPLOAD_URL_TTL_SECONDS = 300;

const s3 = new S3Client();

export const handler: Schema['getUploadUrl']['functionHandler'] = async (event) => {
  const { contentType, sessionToken } = event.arguments;

  // Proof-of-humanness AND session identity in one step: the sessionId comes from the
  // SIGNED token, never from a client argument. This is what makes menu/<sessionId>/ a
  // real ownership boundary — a caller cannot choose someone else's prefix. No valid
  // token, no presigned URL. The exact message matters: the frontend detects it to
  // auto-renew and retry.
  const session = readSessionToken(sessionToken, env.SESSION_TOKEN_SECRET);
  if (!session) {
    throw new Error('Session expired — please try again.');
  }

  // Never trust the client: validate the declared MIME type before signing a URL.
  if (!ALLOWED_CONTENT_TYPES.has(contentType)) {
    throw new Error(`Unsupported content type: ${contentType}`);
  }

  // Key is fully server-derived: signed sessionId + random object id + a fixed
  // extension from the (validated) content type. Nothing the client sent shapes the path.
  const s3Key = `menu/${session.sessionId}/${randomUUID()}.${EXTENSION[contentType]}`;

  const uploadUrl = await getSignedUrl(
    s3,
    new PutObjectCommand({
      Bucket: env.SHISHA_MENU_UPLOADS_BUCKET_NAME,
      Key: s3Key,
      ContentType: contentType,
    }),
    { expiresIn: UPLOAD_URL_TTL_SECONDS },
  );

  return { uploadUrl, s3Key };
};
