import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { randomUUID } from 'node:crypto';
// `env` is generated by Amplify once storage access is granted (see storage/resource.ts).
// It exposes the uploads bucket name in a type-safe way. Red squiggle before the
// first `ampx sandbox` run is expected — the file is generated at deploy time.
import { env } from '$amplify/env/get-upload-url';
import type { Schema } from '../../data/resource';

// Only these image types are accepted for a menu upload.
const ALLOWED_CONTENT_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']);
// How long the presigned PUT URL is valid, in seconds.
const UPLOAD_URL_TTL_SECONDS = 300;

const s3 = new S3Client();

export const handler: Schema['getUploadUrl']['functionHandler'] = async (event) => {
  const { contentType } = event.arguments;

  // Never trust the client: validate the declared MIME type before signing a URL.
  if (!ALLOWED_CONTENT_TYPES.has(contentType)) {
    throw new Error(`Unsupported content type: ${contentType}`);
  }

  // Random key under menu/ so uploads never collide and match the storage path rule.
  const extension = contentType.split('/')[1];
  const s3Key = `menu/${randomUUID()}.${extension}`;

  const uploadUrl = await getSignedUrl(
    s3,
    new PutObjectCommand({
      Bucket: env.SHISHA_MENU_UPLOADS_BUCKET_NAME,
      Key: s3Key,
      ContentType: contentType,
    }),
    { expiresIn: UPLOAD_URL_TTL_SECONDS },
  );

  return { uploadUrl, s3Key };
};
